#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(
		KC_Q,         KC_W,         KC_E,         KC_R,         KC_T,      KC_Y,   KC_U,         KC_I,         KC_O,         KC_P,

		LCTL_T(KC_A), LALT_T(KC_S), LGUI_T(KC_D), LSFT_T(KC_F), KC_G,      KC_H,   RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN),

		KC_Z,         KC_X,         KC_C,         KC_V,         KC_B,      KC_N,   KC_M,         KC_COMM,      KC_DOT, KC_SLSH,

		                                          KC_SPC,     OSL(2),      KC_ENT, KC_BSPC),

	[1] = LAYOUT_split_3x5_2(OSL(4), KC_GRV, KC_QUOT, KC_DQUO, KC_ESC,       KC_PIPE, KC_AMPR, KC_LBRC, KC_RBRC, KC_PERC, KC_EXLM, KC_MINS, KC_PLUS, KC_EQL, KC_HASH, KC_UNDS, KC_AT, KC_LPRN, KC_RPRN, KC_ASTR, KC_NO, LGUI(KC_MINS), LGUI(KC_EQL), KC_CIRC, CW_TOGG, KC_BSLS, KC_TILD, KC_LCBR, KC_RCBR, KC_DLR, KC_TRNS, TG(3), KC_TRNS, KC_TRNS),
	[2] = LAYOUT_split_3x5_2(KC_1, KC_2, KC_3, KC_4, KC_5,       KC_6, KC_7, KC_8, KC_9, KC_0, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_MUTE, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), KC_CAPS, KC_BRID, KC_VOLD, KC_VOLU, KC_BRIU, KC_NO, KC_TRNS, TG(3), KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_3x5_2(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,       KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_F11, KC_F12, KC_RSFT, KC_RGUI, KC_RALT, KC_RCTL, OSL(5), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_NO, KC_ENT, KC_BSPC),
	[4] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,       KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_NO, KC_ENT, KC_BSPC)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




